#!/bin/bash

function install_test_deps {
    pip install pytest requests coverage
}

function start_test_server {
    echo "Starting test server. Log: tests/server.log"
    rm -f tests/server.log
    coverage run -p tests/servertest.py >tests/server.log 2>&1 &
}

function run_tests {
    install_test_deps
    start_test_server
    coverage run -p `which py.test` -s tests/ $@
    exit_code=$?
    stop_test_server
    coverage combine
    coverage report -m
    coverage erase
    exit $exit_code
}

function stop_test_server {
	echo "Stop test server..."
    ps ax | grep tests/servertest.py | grep -v grep | cut -d ' ' -f 1 | xargs kill -INT
}

if [ -z "$1" ]; then
	run_tests $@
else
	$@ 
fi
